[package]
name = "guitar_chord_builder"
version = "0.1.0"
edition = "2024"

[dependencies]
strum_macros = "0.27"
derive-getters = "0.5.0" # Or the latest version

eframe = "0.33.0"  # Use the latest version from crates.io